services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=weather_mood_db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5433:5432'